[package]
name = "verder-helpen-auth-irma"
version = "0.1.0"
authors = ["David Venhoek <david@tweedegolf.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
verder-helpen-sentry = { git = "https://github.com/verder-helpen/verder-helpen-sentry.git" }
verder-helpen-jwt = { git = "https://github.com/verder-helpen/verder-helpen-jwt.git" }
verder-helpen-proto = { git = "https://github.com/verder-helpen/verder-helpen-proto.git" }
log = "0.4.17"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.137"
serde_json = "1.0.81"
serde_yaml = "0.8.24"
strum = "0.24.0"
strum_macros = "0.24.0"
reqwest = { version = "0.11.10", features = ["json"] }
urlencoding = "2.1.0"
base64 = "0.13.0"
josekit = "0.8.0"
askama = "0.11.1"
